config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rentals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rental.rb
# frozen_string_literal: true

class Rental < ApplicationRecord
  validates :id, presence: true, uniqueness: true
  validates :title, presence: true
  validates :category, inclusion: {
    in: %w[Apartment Estate Condo House],
    message: I18n.t('tests.category_invalid')
  }
  validates :bedrooms, comparison: {
    greater_than_or_equal_to: 0,
    message: I18n.t('tests.bedrooms_invalid')
  }
  validates :latitude, comparison: {
    greater_than_or_equal_to: -90,
    less_than_or_equal_to: 90,
    message: I18n.t('tests.latitude_invalid')
  }
  validates :longitude, comparison: {
    greater_than_or_equal_to: -360,
    less_than_or_equal_to: 360,
    message: I18n.t('tests.longitude_invalid')
  }

  def self_link
    "http://localhost:8010/#{self.class.to_s.downcase}s/#{id}.json"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/rentals_controller.rb
# frozen_string_literal: true

class RentalsController < ApplicationController
  before_action :set_rental, only: %i[show edit update destroy]

  # One or more of the following keys must be present: "data", "errors", "meta".

  # GET /rentals or /rentals.json
  def index
    # @rentals = Rental.all
    # warn "DEBUG: index - #{request.url}"
    render json: RentalSerializer.new(Rental.all).as_json
  end

  # GET /rentals/1 or /rentals/1.json
  def show
    # warn "DEBUG: show - #{request.url}"
    render json: RentalSerializer.new(@rental).as_json
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit; end

  # POST /rentals or /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to rental_url(@rental), notice: I18n.t('rental.created') }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1 or /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to rental_url(@rental), notice: I18n.t('rental.updated') }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1 or /rentals/1.json
  def destroy
    @rental.destroy

    respond_to do |format|
      format.html { redirect_to rentals_url, notice: I18n.t('rental.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_rental
    @rental = Rental.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def rental_params
    params.require(:rental).permit(:id, :title, :owner, :city, :latitude, :longitude, :category, :bedrooms, :image,
                                   :description)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/rentals_helper.rb
# frozen_string_literal: true

module RentalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperRentalApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rentals/_form.html.erb
<%= form_with(model: rental) do |form| %>
  <% if rental.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
        <% rental.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text_id, style: "display: block" %>
    <%= form.text_field :text_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :owner, style: "display: block" %>
    <%= form.text_field :owner %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :bedrooms, style: "display: block" %>
    <%= form.number_field :bedrooms %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rentals/_rental.html.erb
<div id="<%= dom_id rental %>">
  <p>
    <strong>Text:</strong>
    <%= rental.text_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= rental.title %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= rental.owner %>
  </p>

  <p>
    <strong>City:</strong>
    <%= rental.city %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= rental.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= rental.longitude %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= rental.category %>
  </p>

  <p>
    <strong>Bedrooms:</strong>
    <%= rental.bedrooms %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= rental.image %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= rental.description %>
  </p>

</div>

app/views/rentals/edit.html.erb
<h1>Editing rental</h1>

<%= render "form", rental: @rental %>

<br>

<div>
  <%= link_to "Show this rental", @rental %> |
  <%= link_to "Back to rentals", rentals_path %>
</div>

app/views/rentals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rentals</h1>

<div id="rentals">
  <% @rentals.each do |rental| %>
    <%= render rental %>
    <p>
      <%= link_to "Show this rental", rental %>
    </p>
  <% end %>
</div>

<%= link_to "New rental", new_rental_path %>

app/views/rentals/new.html.erb
<h1>New rental</h1>

<%= render "form", rental: @rental %>

<br>

<div>
  <%= link_to "Back to rentals", rentals_path %>
</div>

app/views/rentals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rental %>

<div>
  <%= link_to "Edit this rental", edit_rental_path(@rental) %> |
  <%= link_to "Back to rentals", rentals_path %>

  <%= button_to "Destroy this rental", @rental, method: :delete %>
</div>